# Generated by Django 5.2.5 on 2025-08-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_on_vacations',
            field=models.BooleanField(default=False),
        ),
    ]
